# Generated by Django 5.0.6 on 2024-06-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_review_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='email@email.com', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=100),
        ),
    ]
