# Generated by Django 5.0.6 on 2024-06-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
    ]
