# Generated by Django 5.0.6 on 2024-07-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orders_amount_total_alter_orders_cart_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='cart_info',
            field=models.CharField(),
        ),
    ]
