# Generated by Django 5.0.6 on 2024-05-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
