# Generated by Django 5.0.6 on 2024-07-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount_total',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='cart_info',
            field=models.CharField(max_length=255),
        ),
    ]
