# Generated by Django 5.0.6 on 2024-07-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_product_route_alter_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cart_info',
            field=models.TextField(),
        ),
    ]
