name: Generate a build and push to another branch

on:
  push:
    branches:
      - master
  workflow_dispatch: # This allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          pip install -r requirements.txt

      - name: Run migrations
        run: |
          source env/bin/activate
          python manage.py migrate

      - name: Run tests
        run: |
          source env/bin/activate
          python manage.py test

      - name: Use Stripe API Key
        run: |
          source env/bin/activate
          python manage.py your_command_that_uses_stripe
        env:
          STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
